ember-learn/ember-website

- yarn.lock
This is just updating the styleguide version to get access to the fix merged in https://github.com/ember-learn/ember-styleguide/pull/136
> Bumping styleguide version

- app/index.html
This is to improve the accessibility of the website. 
The rest of accessibility issues will be covered in [ember-styleguide](https://github.com/ember-learn/ember-styleguide)
- Related issue: [Issue #234](https://github.com/ember-learn/ember-website/issues/234)
> adding lang attribute to html element to improve the accessibility

- app/templates/editions/octane.hbs
The staging app is up now! So we should update the Octane guides links.
> update links to the Octane Guides preview

- app/templates/editions/index.hbs
This is just because we need to use `{{asset-map}}` for any assets that will get fingerprinted 👍
> fixing missing Tomster image on the editions page

- ember-cli-build.js
Currently svg images cannot be used on the "Who uses Ember.js" site.
This adds svg to the default extensions to be fingerprinted.
<hr>
<hr>
This fixes https://github.com/ember-learn/ember-website/pull/278
> Enable fingerprinting for svg images

- app/router.js
- app/routes/application.js
- package-lock.json
- package.json
Things I have tried:
- `this.on('routeDidChange'` in EmberRouter's `init` - handler not called
- Inject the router service in EmberRouter and add the handler on init - max call stack reached
- Inject the router service in application route and add the handler on init - handler is not called
> Address didTransition deprecation

- ember-cli-build.js
We had an Ember User's image not rendering because they submitted their image as a SVG, this enables the use of SVGs without breaking the links 🎉
> fixing the svg fingerprinting

- app/styles/app.scss
- app/styles/pages/_releases.scss
- app/templates/index.hbs
WAS: EmberConf 2019 callout
IS: No EmberConf 2019 callout
See: `netlify/ember-website/deploy-preview` link below of homepage emberjs.com or Percy!
Note: We need to fix the other Percy's besides the homepage separately, was discussing with @locks on Discord, need to further sync with him.
> Remove out of date EmberConf 2019 callout

- app/styles/_percy-fixes.scss
- app/styles/pages/_home.scss
- app/templates/index.hbs
This is intended to make sure the Call To Action on the homepage works on all smaller mobile screens. It is now using a SVG because we can ensure that it will always use the space available 👍
> making sure the call to action works on smaller mobile sizes

- data/project/ember/lts.md
This updates the year on the [releases page](https://emberjs.com/releases/) to be 2019 instead of 2018 for the LTS channel 🎉 
As far as I can tell this is where that data comes from.
> Bump LTS date to 2019

- app/templates/releases/index.hbs
- data/project/ember/beta.md
I removed the 2.16 LTS from the bottom of the list, as I added the 3.8 LTS to the top of the list. Since 2.18 (now the bottom of the list) expired its final support date back in February, it is reasonable to infer that all prior LTS versions are no longer supported. I also bumped the data so that 3.9 is shown as the current latest release, rather than 3.8.
> Releases page: Fix release version to 3.9, add LTS dates for 3.8

- app/templates/learn/index.hbs
- app/templates/team.hbs
Recently we added Ember Engines on Ember Guides - https://guides.emberjs.com/release/applications/ember-engines/
I think that very important put on ember website the reference to Ember Engines, because he is maintained by ember core team as well 
@jenweber @sivakumar-kailasam
> Adds Ember Engines on ember ecosystem

- package-lock.json
- package.json
The current project version of sass package require a Python. The latest version use [dart-sass](https://sass-lang.com/dart-sass) implementation and `npm i` will work more faster and will work on systems without a Python (Windows 7/10).
> Bump sass and ember-cli-sass to latest versions

- data/project/ember/beta.md
> Corrects the release week for 3.11.0

- data/team-member/stefan-penner.md
...but not actually adding him to archive since he's still on CLI as far as I know and I don't _think_ we want folks in multiple places? Maybe if in the future the alums section also listed what teams people were from :)
> Alumnizing Stef from Framework Team

- .github/stale.yml
See: https://probot.github.io/apps/stale/. I added the Stale app to ember-blog and ember-website (these are the two repos that I have the most context on). I used the defaults from the Stale website. 
Note: Stale bumps issues and pull requests.
Tagging @jenweber cause we talked about it at the meeting, and @hakilebara based on his interests re: Ember-Learn Open Pull Requests Statistics. I think that this bot could really help us with keeping the "backlog" up to date, even if it's a #wontfix. I will also share in the Learning Channel.
Also added to ember-blog: https://github.com/ember-learn/ember-blog/pull/179
> Add Stale app to repo

- .github/stale.yml
- Make settings 2x longer for issues. If it's been open for 4mo, seems safe to push to project management tool e.g. GitHub Projects / Notion / other we are using? 
- Change label to `stale` vs. `wontfix` (I can do this manually as well, seems more accurate.)
If we are cool with this, I can make the same changes on ember-blog.
> Update stale settings

- data/project/ember/beta.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
After waiting a couple of weeks after the blog post came out, I updated the data pages to get the release pages in sync.
Open questions:
1. What is the projected date for 3.12 release? I used change log date for 3.11 release date, since that has been used in the past, but six weeks from change log date is 5th August, which is very soon. Official release is generally quoted as the day the blog post goes out. Six weeks from blog post date is 26th August. Being conservative, I used the later date. Please advise.
2. The Change Log for Ember Data shows version 3.12.0-beta-1, but NPM shows version 3.12-beta-0, and no beta-1. In my changes, I used the latter because it would work.
Notes: In NPM, the LTS tag for ember-source is 3.8.1, even though there is a 3.8.3. The LTS tag for ember-data is …
> Updated release page data for release of 3.11 and beta of 3.12

- app/templates/editions/octane.hbs
This is a follow up on a to-do item from the last octane team meeting.
The verbage is copy-paste from the Octane Plan blog post. I added a bit to the FAQs as well.
> update description of Octane for the landing page

- app/templates/editions/index.hbs
> use octane mascot in editions page

- app/templates/editions/octane.hbs
Previously the guides link was pointing to the "Templating" section. Also added link to tutorial.
> Update guides links

- data/project/ember/beta.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
On the [releases page](https://emberjs.com/releases/release), we refer to version numbers 3.12 and 3.13. This change increments those version numbers to 3.13 and 3.14.
> bump version listed from 3.12 to 3.13, and 3.13 to 3.14.

- app/templates/ember-users.hbs
The break was adding an unintentional space to the hyperlink.
WAS:
IS: 
From Percy:
> Copy fix to /ember-users page

- app/templates/index.hbs
Using the audit mentioned in #234, I added some aria-labels for the main homepage. These include:
- labels for everything in the "gears" div
- a label for the EmberConf site, linked to the logo
Hope this is useful!
> Add some more aria-labels to create discernable links

- app/templates/guidelines.hbs
fixes https://github.com/ember-learn/ember-website/issues/437
Some comments:
- I didn't find a class to highlight the `General Goals` text as on the old page
- I'm not convinced about the padding between the header and the `<h1>` (seems a bit big), but it's due to the container, applying `padding-top-medium` didn't change anything.
> Update guidelines page markup

- app/templates/releases/lts.hbs
Following the [release of 3.13, 3.12 has now been promoted to LTS][1]. This PR adds 3.12 to the LTS page. The support/bugfix end dates are based on previous releases (i.e. +7 / +5 months).
[1]: https://blog.emberjs.com/2019/09/25/ember-3-13-released.html
> Ember.js 3.12 is promoted to LTS

- package-lock.json
- package.json
This removes the need to use github urls and branch markers 🎉 and hopefully it should make Netlify a bit happier 😂
> update styleguide to use new pre-release from npm

- app/templates/community/index.hbs
fixes #432 
There was no style for floated images so I used the `layout-grid` class and put them in a 2 col space with the text in a 4 col space beside them. Some of the images are not high res enough and look a bit pixelated.
Also I bumped the video res from 640x360 to 854x480 to make it fit better under the 2 col layout above it.
> Updated markup for community page

- app/controllers/ember-users.js
- app/templates/ember-users.hbs
This PR addresses the issue #436 . In addition to the styleguide doc, I looked at PRs #450 and #455 for reference.
There are a few remaining issues that I couldn't solve on first attempt:
- The doc suggests, in order to use `card-link` option to make the entire `<EsCard>` interactive, I'd need to yield an `<a>` tag. Since an anchor needs text (content), I temporarily added the company's name. I'm not sure if there's an additional class name or attribute that I can pass to the card to make the text invisible.
- An alternative approach may be to not use `@image` attribute, but instead add `<img>` tag inside the `<a>` tag, as done previously?
- (1) I wasn't sure how to set class names to render fewer cards for smaller resolutions. (2) The current Ember website shows 5, 3, 2, or 1 card(s). …
> Updated markup for About - Who Uses Ember page

- app/templates/sponsors.hbs
This PR address the issue #443.
> Updated markup for About - Sponsors page

- app/templates/community/meetups-getting-started.hbs
This PR addresses the issue #435 .
After update (top half):
After update (bottom half):
> Updated markup for Community - Meetups Getting Started

- data/project/ember/beta.md
The previous release under "Upcoming releases" on the [releases page](https://emberjs.com/releases/) is incorrect (should be 3.14.0).
Before:
After:
Percy snapshot: https://percy.io/Ember/Ember-Website/builds/3413020/view/209625384/1280?mode=diff&browser=firefox&snapshot=209625384
> fix(release): fix initialVersion in beta channel data

- app/styles/app.css
- app/templates/community/meetups/index.hbs
Fixes https://github.com/ember-learn/ember-website/issues/433
More styles are needed to finish this page. Specifically:
- For the map to be visible, there should be styles for the `leaflet-container` class with the size of the container. On the previous version it was:
```css
.leaflet-container {
height: 400px;
}
```
- The location icons (previously part of the `<li>` styles) were added here as images, but I had to add inline-styles for now to make the sizing similar to what it was. 
- The list of locations was previously shown in 4 columns, with the current grid is a bit hard to do that. I tried `col-1` but some names are long and the text gets wrapped, so I went with `col-2-large col-4`. 
| Desktop | Mobile| 
| ---|---|
|<img width="1173" alt="Screen Shot 2019-11-01 at 16 47 18" …
> Update community meetup page

- app/styles/components/addon-tabs.css
- app/templates/components/addon-tabs.hbs
- app/templates/index.hbs
This now fixes all the remaining Axe warnings on the landing page (one more will be fixed with https://github.com/ember-learn/ember-styleguide/pull/278)
If you run Axe after this is merged it will show a bunch of "cannot determine contrast ratio because of background image" 🤔 is there any way that we can disable this? Most of our background images are just there for frills that don't cross most of the text so if we could get Axe to ignore the background images completely then it would be more useful in this case
> fix axe warnings

- app/index.html
- app/templates/head.hbs
This is just an extension of https://github.com/ember-learn/ember-website/pull/379 that applies the same title information to the twitter and OG metadata fields
As I mentioned in https://github.com/ember-learn/ember-website/pull/379#issuecomment-523373148 we need to have a more full review of metadata and that can be done after the redesign is released.
This closes https://github.com/ember-learn/ember-website/issues/537 and I have made sure that titles are updating as you navigate through the app 👍
> fix title metadata

- app/templates/guidelines.hbs
I used a `let` block to avoid duplicating that value if we ever need to
change it again.
> fix dead link in guidelines.hbs

- app/styles/app.css
Leaflet uses z-index values for it's inner dom structure which makes them apear above the navigation bar dropdowns.
Closes #569
> Add a z-index to the Leaflet map wrapper element

- app/templates/community/index.hbs
I noticed the [video on the community page](https://deploy-preview-361--ember-website.netlify.com/community) had inconsistent whitespace which I assume is a remnant from the previous version.
I also noticed the images are a bit blurry do to them being upscaled and that especially noticable on mobile devices. Are there any plans of them being replaced with svg versions?
If not, I personally wouldn't upscale them and just center the image on mobile, and left / right align them on larger devices (depending on how they are positioned next to the text). Thoughts? @MelSumner @mansona 
PS. I know things like this is very nitpicky so let me know if it shouldn't be reported :smile:
> Make the video whitespace consistent

- app/templates/ember-users.hbs
- Fixed using @pichfl's advice of adding `well-16/9` class ([reference](https://github.com/ember-learn/ember-website/issues/582#issuecomment-587568312))
> Fixes issue #582

- data/project/ember/beta.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
Followed: https://github.com/ember-learn/ember-website/pull/490
- Assumed date was today, Feb 18
- `nextDate` = Mar 25, 6wk from initialReleaseDate
- `initialReleaseDate` = Feb 12, date of blog post
- For version #s, went to GitHub repo links
Resolves: https://github.com/ember-learn/ember-website/issues/568
Let me know if needs edits or feel free to commit directly to the branch!
> 🐛 Update releases page for 3.16

- app/styles/components/cta-emberconf.css
Fixes #590 
Tested in Firefox, Edge (non-webkit) and IE11. IE11 has other issues due to the css variables though.
> Fix EmberConf CTA layout issue

- app/templates/index.hbs
On the homepage currently the "Ember Weekly" link (in the podcast section?) is linking to Ember Weekend and there is no link to Ember Weekly proper. This PR fixes the podcast link and adds Ember Weekly as to the Books and Blogs section since I thought that is the closest approximation as a reading resource
> Fix Ember Weekend and Ember Weekly Homepage Links

- app/templates/releases/lts.hbs
- data/project/ember/lts.md
This PR addresses https://github.com/ember-learn/ember-website/issues/617.
- Updated the LTS Markdown data to show the most recent LTS version (3.16.6)
- Updated the LTS schedule table to show LTS versions that are currently supported (3.16, 3.12, 3.8)
- Added a paragraph about LTS versions that are no longer supported (3.4, 2.18, 2.16, 2.12, 2.8, 2.4)
I found determining the dates for bug fix, security patch, and EOL (end of life) from Ember blog posts to be confusing and error-prone. The 36- and 54-week patterns didn't always seem to occur.
Instead, I looked at the [changelog](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md) as the source of truth.
For bug fix and security patch, I took the x.x.0 minor release date and asked Google to add 36 weeks and 54 weeks, accordingly, …
> Updated Releases - LTS page

- CONTRIBUTING.md
- app/controllers/releases/lts.js
- app/helpers/add-weeks.js
- app/templates/releases/lts.hbs
- tests/integration/helpers/add-weeks-test.js
This PR addresses the issue #634 .
When I worked on PR #627, I was confused by when exactly a release of Ember gets promoted to LTS and how to calculate the dates for bugfixes and security patches.
In this PR, I made 3 changes.
First, I corrected the dates that are currently shown on the [LTS Channel page](https://emberjs.com/releases/lts/).
Second, I created a helper called `add-weeks` to prevent human error in finding the dates for bugfixes and security patches. The dates for LTS promotion are stored in the `releases.lts` controller. (They could be returned from the route's `model` hook, but the hook was used for something else and I didn't feel like complicating the PR.)
Lastly, I documented how one can check dates related to LTS releases in `CONTRIBUTING.md` so that anyone can update …
> Fixed dates that appear in LTS schedule

- data/project/ember/beta.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
The release data on the site for latest and beta has been out of date since 3.16 went LTS, so before 3.18 got as far as a blog post, I figured I'd submit the change for 3.17. Hopefully I got everything right.
> Updating release data to 3.17

- app/templates/components/team-list.hbs
WAS: 
Twitter icon appears w/ no link
IS:
> Make Twitter optional on team member page

- app/controllers/releases/lts.js
- app/templates/releases/lts.hbs
- data/project/ember/beta.md
- data/project/ember/lts.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
@bouke kindly informed us on [Discourse](https://discuss.emberjs.com/t/ember-js-ember-3-21-released/18183/2) that we didn't update the Releases pages after `v3.20` was promoted to LTS.
I recommend reviewing commits one at a time.
> Updated Releases pages for v3.21 release

- app/templates/index.hbs
The copy mentions community resources, so we would maybe need to change that with this PR. Wanted to kick this off re: https://github.com/ember-learn/ember-website/issues/609
@mansona Did you have something else in mind? I was thinking we could potentially list the Blog the way that Discuss and Discord are listed, in the rectangle?
Aside: Should we consider having Discord before Discuss, since it's a lot more active?
cc @chrisrng in case interested, no worries if not
> Add Ember Times to the homepage somewhere

- .eslintrc.js
- app/adapters/application.js
- app/components/high-charts.js
- app/models/feature.js
- app/models/meetup.js
- app/models/project.js
- app/models/showcase.js
- app/models/sponsor.js
- app/models/team-member.js
- app/models/tomster.js
- app/models/user.js
- app/serializers/application.js
Fixing `ember/use-ember-data-rfc-395-imports` and `no-prototype-builtins` rules as part of #672
> fixing two of jslint issues as part of 672

- data/project/ember/release.md
- data/project/emberData/release.md
We had a 1-day delay in compiling API docs and publishing the blog post for release announcement. For consistency, let's shift the `date` in `release.md` by 1.
> Adjusted blog post release date

- app/templates/learn/index.hbs
Given that the tracking initiative is not really representative of the current state of development and RFC Stages will eventually replace it, I think we should not point our community to it.
> Remove RFC Tracking section

- app/templates/releases/index.hbs
- data/project/ember/beta.md
- data/project/ember/lts.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
~⚠️ This is work in progress.~
We're waiting for `ember-cli v3.23` and blog post to be released before merging this pull request. The today's date in `release.md` will need to coincide with the release date of the blog post.
> Updated Releases pages for Ember v3.23 release

- data/project/ember/beta.md
`ember-source` recently released `v3.24.0-beta.3` so I wanted to update the [Beta Channel](https://emberjs.com/releases/beta) page.
- https://github.com/emberjs/ember.js/blob/v3.24.0-beta.3/CHANGELOG.md#v3240-beta3-december-21-2020
> Updated Beta Channel page

- data/project/ember/beta.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
I followed the instructions in the Markdown files, then updated release versions and dates for the upcoming 3.24 release.
⚠️ This pull request can be merged after the release blog post is published (estimated date: Jan 7). If there's a delay, the today's date in `release.md` will need to coincide with the release date of the blog post.
> Updated Releases pages for Ember v3.24 release

- .eslintrc.js
- config/environment.js
- package.json
- tests/acceptance/visual-routes-test.js
- tests/index.html
- tests/test-helper.js
- yarn.lock
Over the next month, I want to make several pull requests so that we can upgrade `ember-source` from `v3.16` to `v3.24`.
In this pull request, I updated lint- and test-related development dependencies to their latest. This involved updating them to the next major version, with breaking changes.
I addressed failing lint errors by temporarily turning off the rules. I think most JS lint errors can be fixed by refactoring classic components to Glimmer components (outside of scope of this PR).
While upgrading `ember-a11y-testing`, I noticed we don't actually use the addon to run accessibility audits in tests. Let's address this problem separately.
> Upgraded dependencies (Part 2)

- app/components/project-listing/beta/component.js
- app/components/tomster-list.js
- app/helpers/capitalize.js
- tests/integration/components/addon-tabs-test.js
- tests/integration/components/addon-tabs/panel-test.js
- tests/integration/components/addon-tabs/tab-test.js
- tests/integration/components/black-lives-matter-banner-test.js
- tests/integration/components/cta-emberconf-test.js
- tests/integration/components/ecosystem-icon-test.js
- tests/integration/components/ecosystem-icons-test.js
- tests/integration/components/ember-survey-test.js
- tests/integration/components/grid-dots-test.js
- tests/integration/components/high-charts-test.js
- tests/integration/components/homepage-image-grid-test.js
- tests/integration/components/project-listing-test.js
- tests/integration/components/project-listing/beta-test.js
- tests/integration/components/release-timeline-test.js
- tests/integration/components/remove-spinner-test.js
- tests/integration/components/team-list-test.js
- tests/integration/components/terminal-code-test.js
- tests/integration/components/tomster-list-test.js
- tests/unit/serializers/application-test.js
Over the next month, I want to make several pull requests so that we can upgrade `ember-source` from `v3.20` to `v3.24`.
In this pull request, I added unit tests for `application` serializer and default rendering tests for components.
The tests for components, in particular, will help us migrate the components layout from classic pre-Octane (template files in `app/templates`) to classic Octane (colocated in `app/components`).
The default rendering tests also help us check that the code in a backing class can run without error when the arguments are undefined.
> Added tests to better document the project (Part 2)

- tests/acceptance/about/legal-test.js
- tests/acceptance/community-test.js
- tests/acceptance/community/black-lives-matter-test.js
- tests/acceptance/community/meetups-test.js
- tests/acceptance/community/meetups/assets-test.js
- tests/acceptance/editions-test.js
- tests/acceptance/editions/octane-test.js
- tests/acceptance/ember-community-survey-2019-test.js
- tests/acceptance/ember-users-test.js
- tests/acceptance/guidelines-test.js
- tests/acceptance/index-test.js
- tests/acceptance/learn-test.js
- tests/acceptance/logos-test.js
- tests/acceptance/mascots-test.js
- tests/acceptance/mascots/commission-test.js
- tests/acceptance/mascots/faq-test.js
- tests/acceptance/mascots/payment-test.js
- tests/acceptance/releases-test.js
- tests/acceptance/releases/beta-test.js
- tests/acceptance/releases/canary-test.js
- tests/acceptance/releases/lts-test.js
- tests/acceptance/releases/release-test.js
- tests/acceptance/security-test.js
- tests/acceptance/sponsors-test.js
- tests/acceptance/teams-test.js
Over the next month, I want to make several pull requests so that we can upgrade `ember-source` from `v3.20` to `v3.24`.
In this pull request, I added application tests that run an accessibility audit on each route.
To limit the scope of this pull request, when we violate an axe-recommended rule in a route, I made an exception to that rule in the corresponding test. We can address fixing the violation in a separate issue and pull request.
> Added tests to better document the project (Part 4)

- tests/acceptance/about/legal-test.js
- tests/acceptance/community-test.js
- tests/acceptance/community/black-lives-matter-test.js
- tests/acceptance/community/meetups-getting-started-test.js
- tests/acceptance/community/meetups-test.js
- tests/acceptance/community/meetups/assets-test.js
- tests/acceptance/editions-test.js
- tests/acceptance/editions/octane-test.js
- tests/acceptance/ember-community-survey-2019-test.js
- tests/acceptance/ember-users-test.js
- tests/acceptance/guidelines-test.js
- tests/acceptance/index-test.js
- tests/acceptance/learn-test.js
- tests/acceptance/logos-test.js
- tests/acceptance/mascots-test.js
- tests/acceptance/mascots/commission-test.js
- tests/acceptance/mascots/faq-test.js
- tests/acceptance/mascots/payment-test.js
- tests/acceptance/releases-test.js
- tests/acceptance/releases/beta-test.js
- tests/acceptance/releases/canary-test.js
- tests/acceptance/releases/lts-test.js
- tests/acceptance/releases/release-test.js
- tests/acceptance/security-test.js
- tests/acceptance/sponsors-test.js
- tests/acceptance/teams-test.js
- tests/helpers/page-title.js
A new Ember 3.24 app will have `ember-page-title` installed. The `ember-website` app already uses `ember-page-title`, but the installed addon is 1 major version behind.
Before we upgrade `ember-page-title` to `v6.x`, we must consider:
- Replacing the `{{title}}` helper with `{{page-title}}` helper
- Updating `app/templates/head.hbs` (the template mentions a `<title>` element)
To help with replacing the `{{title}}` helper with `{{page-title}}` with confidence, I added assertions for each route that we already test. The custom assertion is based on [the one from `ember-page-title`](https://github.com/ember-cli/ember-page-title/blob/f8fff84c142aab9b661e395c1586110fdda495f2/tests/helpers/get-page-title.js).
In general, it probably isn't a good idea to test an external addon (we should assume …
> Added tests to better document the project (Part 5)

- app/templates/about/legal.hbs
- app/templates/application.hbs
- app/templates/community.hbs
- app/templates/community/meetups-getting-started.hbs
- app/templates/community/meetups/assets.hbs
- app/templates/community/meetups/index.hbs
- app/templates/editions/index.hbs
- app/templates/editions/octane.hbs
- app/templates/ember-community-survey-2016.hbs
- app/templates/ember-community-survey-2017.hbs
- app/templates/ember-community-survey-2018.hbs
- app/templates/ember-community-survey-2019.hbs
- app/templates/ember-community-survey-2020.hbs
- app/templates/ember-users.hbs
- app/templates/guidelines.hbs
- app/templates/index.hbs
- app/templates/learn/index.hbs
- app/templates/logos.hbs
- app/templates/mascots/index.hbs
- app/templates/releases.hbs
- app/templates/releases/beta.hbs
- app/templates/releases/canary.hbs
- app/templates/releases/lts.hbs
- app/templates/releases/release.hbs
- app/templates/security.hbs
- app/templates/sponsors.hbs
- app/templates/team.hbs
Resolves https://github.com/ember-learn/ember-website/issues/711
According to https://github.com/ember-cli/ember-page-title#upgrading-notes-for-5x-to-6x I had to remove usage of `HeadLayout` from `application.hbs`
> Replace deprecated title helper to page-title

- app/controllers/application.js
- app/utils/replace-links.js
- tests/unit/utils/replace-links-test.js
Over the next month, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.
In this pull request, I extracted the function `replaceLinks` from the `application` controller to a utility file called `replace-links`.
This way, we can write unit tests to document what `replaceLinks` is supposed to do, and help a contributor easily rewrite the `application` controller in native class.
I made a few refactors so I recommend reviewing the commits one by one.
> Extracted replaceLinks from the application controller

- app/controllers/community/meetups/index.js
- app/controllers/learn/index.js
- app/controllers/releases/index.js
- app/controllers/team.js
- app/models/project.js
- tests/unit/controllers/application-test.js
- tests/unit/controllers/community/meetups/index-test.js
- tests/unit/controllers/ember-community-survey-2016-test.js
- tests/unit/controllers/ember-community-survey-2017-test.js
- tests/unit/controllers/ember-community-survey-2018-test.js
- tests/unit/controllers/ember-community-survey-2019-test.js
- tests/unit/controllers/ember-users-test.js
- tests/unit/controllers/mascots/index-test.js
- tests/unit/controllers/releases/index-test.js
- tests/unit/controllers/releases/lts-test.js
- tests/unit/controllers/sponsors-test.js
- tests/unit/controllers/team-test.js
- tests/unit/models/project-test.js
Over the next month, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.
In this pull request, I added unit tests for controllers. These tests, in particular, assert how we sort data that are returned from the `model` hook.
Having these tests will help us rewrite controllers in native class. I imagine that, if we were to create components to break down large route templates, we can reuse the test setups that I created in this pull request.
I recommend reviewing commits one by one. Each commit makes a small, meaningful change.
> Added tests to better document the project (Part 7)

- tests/unit/controllers/community/meetups/index-test.js
- tests/unit/controllers/ember-users-test.js
- tests/unit/controllers/releases/index-test.js
- tests/unit/controllers/sponsors-test.js
- tests/unit/controllers/team-test.js
- tests/unit/routes/application-test.js
- tests/unit/routes/community/meetups/index-test.js
- tests/unit/routes/ember-community-survey-2016-test.js
- tests/unit/routes/ember-community-survey-2017-test.js
- tests/unit/routes/ember-community-survey-2018-test.js
- tests/unit/routes/ember-community-survey-2019-test.js
- tests/unit/routes/ember-users-test.js
- tests/unit/routes/learn-test.js
- tests/unit/routes/mascots-test.js
- tests/unit/routes/releases-test.js
- tests/unit/routes/releases/beta-test.js
- tests/unit/routes/releases/canary-test.js
- tests/unit/routes/releases/index-test.js
- tests/unit/routes/releases/lts-test.js
- tests/unit/routes/releases/release-test.js
- tests/unit/routes/sponsors-test.js
- tests/unit/routes/statusboard-test.js
- tests/unit/routes/team-redirect-test.js
- tests/unit/routes/team-test.js
Over the next month, we'll upgrade `ember-source` from `v3.20` to `v3.24` and ensure that we follow recommended practices in Ember Octane.
In this pull request, I added unit tests for routes. These tests, in particular, assert what we return from the `model` hook.
> Added tests to better document the project (Part 8)

- app/controllers/application.js
- app/utils/header-links.js
- tests/unit/utils/header-links-test.js
In #745, we created a route called `browser-support`. To help people find this page, we want to add a link to the page to the top navigation menu, between `Releases - Editions` and `Releases - Deprecations`.
The problem is, the data that define the menu links come from the addon [ember-styleguide](https://github.com/ember-learn/ember-styleguide/blob/v5.1.0/addon/constants/links.js). As a result, we need to make a pull request in that repo, then upgrade the addon in `ember-website`.
A complication would arise because we haven't yet upgraded the addon to the latest version. There were breaking changes between `v4` and `v5`.
In this pull request, I duplicated the data from `ember-styleguide`, then updated the data so that we will show `Browser Support` between `Editions` and `Deprecations`. …
> Added Browser Support to top navigation menu

- app/styles/app.css
- package-lock.json
- package.json
This PR updates the ember-styleguide to the latest version 🎉 
The latest breaking change for ember-styleguide was removing landing page specific styles (things that don't make sense in the blog or other sites). This PR just adds those styles back in to the website as app-specific styles 👍
> Update ember-styleguide to v5

- app/templates/sponsors.hbs
This pull request can close https://github.com/ember-learn/ember-website/issues/755. I opened a PR first so that we may use the deploy preview website to provide one another feedback better.
A couple of links in case we want to embed buttons.
- https://docs.opencollective.com/help/collectives/widgets
- https://github.community/t/embed-sponsor-button-seems-to-be-broken/118493/2
> Added links to Open Collective and GitHub Sponsors to the Sponsors page

- app/templates/releases/index.hbs
This hides the title on mobile devices and makes it consistent with the Tomster statues.
> Hide the "Upcoming releases" title on mobile devices

- app/controllers/releases/lts.js
- data/project/ember/beta.md
- data/project/ember/lts.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
I noticed that I was installing 3.25 while the website is unaware of this version. So I've updated it, similar to the changes in #695.
Feel free to squash merge these changes. I've made them through the Github UI and have no idea how to squash those commits.
> Updated Releases page to announce 3.25 release

- .netlifyredirects
- app/router.js
- app/routes/survey.js
- app/templates/survey.hbs
- app/utils/header-links.js
- tests/acceptance/index-test.js
- tests/acceptance/survey-test.js
- tests/unit/routes/survey-test.js
I think this PR can address 2 suggestions from @MelSumner:
- Have `survey` route redirect to `ember-community-survey-2021` (https://github.com/ember-learn/ember-website/pull/780)
- Add `survey` route as a landing page for survey results pages (https://github.com/ember-learn/ember-website/issues/765)
When you visit `/survey` URL, you will be redirected to `/ember-community-survey-2021`.
I recommend reviewing commits one by one. Each commit makes a small, meaningful change.
> Created survey route

- app/controllers/ember-community-survey-2019.js
- app/controllers/ember-community-survey-2020.js
While working on #784, I realized that several configuration objects were copy-pastes from 2019, and without additional data for 2020. Since they don't have data for 2020, let's remove them so that we can reduce bundle size and the amount of code that we need to maintain.
I also marked configuration objects in 2019 and 2020 that weren't analyzed and rendered in the template, but did have data for that year.
> Removed unused code (Part 2)

- app/router.js
It seems this route is not needed anymore because of the Netlify redirect? Feel free to close if I'm mistaken!
> Remove blog route

- app/router.js
- app/routes/not-found.js
- app/templates/not-found.hbs
- tests/acceptance/not-found-test.js
- tests/unit/routes/not-found-test.js
Far from perfect, but at the moment non-existent URLs return a blank screen.
Let me know if I should update anything related to UI, UX, A11Y, copy and so on.
> Add not-found route

- app/controllers/ember-community-survey-2017.js
- app/controllers/ember-community-survey-2018.js
- app/controllers/ember-community-survey-2019.js
- app/controllers/ember-community-survey-2020.js
- app/templates/ember-community-survey-2020.hbs
Splines, which encourage a viewer to interpolate data, are better reserved for data that are continuous, not discrete.
I rendered `How likely are you to recommend Ember?` charts using `VerticalBarChart` class so that we can avoid creating a `SplineChart` class unnecessarily.
> Replaced spline charts with vertical bar charts (categorical data)

- app/styles/app.css
- app/styles/components/lts-table.css
- app/templates/releases/lts.hbs
I felt like the readability/alignment of the LTS table could slightly be improved. Hope this is okay.
Before:
After:
> Improve LTS table alignment

- app/index.html
Relates to: https://github.com/ember-learn/ember-website/pull/803 and https://github.com/ember-learn/ember-blog/pull/873
//
I'm not sure if this is the best approach (was originally trying to add the host so that the relative URL wouldn't be `/images/...`), but will sync us up with the blog and look better on Twitter for now. Let me know what you think.
May make sense to have a separate repo for shared assets?
WAS:
IS:
> Hardcode full path to social image to match ember-blog

- app/controllers/ember-community-survey-2018.js
- ember-cli-build.js
This is a follow-up PR to #810. We discovered that there was 1 use of Highcharts' `drilldown` feature, but the feature did not work in the production site. This PR cleans up remaining code.
> Removed drilldown (does not work)

- app/locations/trailing-history.js
- config/environment.js
This implements a trick that we use in all Empress projects to make sure that the url in the browser always matches what you would expect when you navigate to page on the website. It's a little bit hard to explain, and the ramifications are hard to quantify (and vast) but I will be able to explain with a simple statement and an example: 
After merging this PR, when you are navigating around the website you will **always** see a trailing `/` at the end of the URL. 
For example: Right now if you visit a sub-page of the website such as the logos page you will always see a trailing slash regardless if you put it in the url bar. Another way of expressing it is that if you visit https://emberjs.com/logos or https://emberjs.com/logos/ the browser will always add the trailing slash. 
In the …
> implement trailing-history location type

- app/components/teams/team/member.hbs
- ember-cli-build.js
I had encountered a `undefined is not a function` while working on #831. Both Simon and I were unable to reproduce the error afterwards, so I think I might have caused a package installation issue before.
I checked that:
- After running the app locally, I can visit http://localhost:4200/teams without encountering the `undefined is not a function` error.
- I can run tests locally and see all tests pass.
> Restored <ResponsiveImage> invocation

- data/project/ember/beta.md
- data/project/ember/lts.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
I used https://libraries.io/npm/ember-source/versions and https://libraries.io/npm/ember-data/versions.
> Announced Ember v3.26 release

- app/controllers/ember-community-survey-2017.js
- app/controllers/ember-community-survey-2018.js
- app/templates/ember-community-survey-2017.hbs
- app/templates/ember-community-survey-2018.hbs
- app/utils/highcharts/spline-chart.js
- tests/unit/utils/highcharts/spline-chart-test.js
This pull request continues work from #838.
Until now, we rendered 4 highly customized spline charts in 2017 and 2018 survey results. These charts superimposed graphs in an attempt to indicate how a trend might have changed over time.
The problem with this approach is the high customization. We overrode the default tooltip with a complex, untested function and could not reuse the spline chart class to visualize any other data application.
A simpler approach can reduce the bundle size (by ~1.2 KB, gzipped), allow us to reuse the class for other data applications, and increase maintainbility. In addition, the new graph can help a general public understand the message that we want to tell with historical data:
> Updated SplineChart class

- package-lock.json
- package.json
This is designed to fix the problem identified in https://github.com/ember-learn/ember-styleguide/pull/356 and https://github.com/ember-learn/ember-website/issues/807
The need for this is hard to explain but @nickschot does the best explanation in this comment: https://github.com/ember-learn/ember-website/issues/807#issuecomment-824705786
I attempted to install this in ember-styleguide so it would trickle down to all apps using it but that doesn't work, there are some issues with using it in a nested addon 🤔 
Closes: https://github.com/ember-learn/ember-website/issues/807
Closes: https://github.com/ember-learn/ember-styleguide/pull/356
> install ember-cli-clean-css to fix the clean-css over-optimisation bugs

- app/templates/community/index.hbs
It looks like the Ember Times moved from Goodbits to Substack at some point. This updates the link on the community page.
> Update Ember Times link to new Substack site

- data/project/ember/beta.md
The beta release page currently shows that `3.27b3` is the latest beta version for `ember-source`, although `3.27.5` has been released. For posterity, the incongruence was due to a delay in `ember-cli@3.27` release.
In the meantime, let's update the beta version to show `3.27b4`.
Related discussion: https://github.com/ember-learn/ember-website/issues/261#issuecomment-864232374
> Updated beta release page

- data/project/ember/beta.md
- data/project/ember/release.md
- tests/integration/data/releases-test.js
These dates should align with https://github.com/ember-learn/ember-blog/pull/995, I would appreciate a gut check from @kategengler on them.
> Update release dates for 3.28

- .github/workflows/ci.yml
- https://github.com/percy/exec-action#deprecated
> Replaced @percy/exec-action (deprecated) with @percy/cli

- data/project/ember/beta.md
- data/project/ember/lts.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
In #878, the update to https://emberjs.com/releases/ resulted in displaying the latest minor version. Unfortunately, the page can become out-of-date when we don't regularly update the data files.
In a separate pull request, I will remove the unused fields in the data files for easier maintenance. To my knowledge, some fields had been used to provide data to the `<Releases::ReleaseTimeline>` component, which no longer exists.
> Provided the latest minor releases for Ember 3.28

- app/controllers/teams.js
- package-lock.json
- package.json
This caching isn't even really *necessary*, but it doesn't hurt; in any case, if we want to use caching here, it makes sense to do it in the idiomatic way we would recommend instead of using the primitives for it.
> Use idiomatic caching for teams list

- app/components/teams/team/member.hbs
- app/styles/components/team-list.css
Remove unwanted pink underline from social links on Team page
Fixes #893
> Remove social link underline

- app/utils/highcharts/area-spline-chart.js
- app/utils/highcharts/horizontal-bar-chart.js
- app/utils/highcharts/pie-chart.js
- app/utils/highcharts/spline-chart.js
- app/utils/highcharts/vertical-bar-chart.js
- tests/unit/utils/highcharts/area-spline-chart-test.js
- tests/unit/utils/highcharts/horizontal-bar-chart-test.js
- tests/unit/utils/highcharts/pie-chart-test.js
- tests/unit/utils/highcharts/spline-chart-test.js
- tests/unit/utils/highcharts/vertical-bar-chart-test.js
A feature was requested in #934. Namely, when a chart doesn't have multiple series, we hide the legend because the context is assumed to be clear.
I updated the utility files so that the feature will apply to all survey charts from 2015 to 2022.
The pull request can be divided into 3 parts. It may help to toggle the `Hide whitespace` option on GitHub.
- Commits 1-5: Used the `beforeEach` hook to use a common set of data across tests. Updated test descriptions and comments so that they may make more sense to a new contributor.
- Commits 6-10: Declared `chart` and `rawData` as tracked properties so that Ember can recompute values that depend on these properties.
- Commits 11-14: Allowed charts to hide legend when `series` has 0 or 1 element(s). (The `legend` key does not apply to pie charts …
> Refactored chart utilities, conditionally hid the chart legend

- data/project/ember/beta.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
I used dates from the libraries.io links, but I wasn't sure about the relationship with `cycleEstimatedFinishDate` and `nextDate`
Also Ember Data doesn't have a 4.4.0-beta release, is it correct to leave at the last 4.3.0-beta?
If this was done correctly for 4.3.0, I'll submit another PR for the pending 4.4.0 release.
> Update release pages for 4.3.0

- app/templates/index.hbs
submitting as per @wifelette's request
EmberConf was in april but the emberjs.com website still features a CTA for EmberConf on the homepage.
This PR remove the CTA from the homepage.
> remove emberconf cta from homepage

- app/controllers/releases/lts.js
- app/templates/releases/lts.hbs
- data/project/ember/beta.md
- data/project/ember/lts.md
- data/project/ember/release.md
- data/project/emberData/beta.md
- data/project/emberData/release.md
I don't think these are totally correct, but it's better than what we had.
I think we need to remove this specificity in the app and link to the release pages in GitHub, long term.
> 4.5 Release - Update some release dates/versions

- app/templates/community/index.hbs
- Fall 2018 is no longer 'recently'!
- 'respective' is not quite the right word there, and isn't adding anything to the sentence, so drop it!
**Alternative:** it’s been four years. Do we still want this *at all*? I could also just delete this whole parenthetical!
> Update langugae about move from Slack to Discord

- app/templates/releases/index.hbs
This updates our description of our approach to major versions and SemVer to include our major version cadence and better explain how we approach minor and major versions and editions, using the text from the RFC.
> Update releases index for RFC 0830

- app/templates/index.hbs
Adds a link to Ember Fest videos: https://www.youtube.com/@emberfest/videos
> Add Ember Fest videos to videos links

- app/templates/releases/index.hbs
If merged, this PR tries to clarify some of the language used on the release overview page to show where folks can find different versions of Ember that are supported (without adding additional maintenance overhead).
> Update some prose on releases overview page

- package-lock.json
- package.json
Bumps styleguide from v6 to v8. The breaking changes were because of old node support drops (v10, v12).
After this is merged we can also remove the EsHeader links customisation from this repository.
> Update ember-styleguide to v8.4.0

- app/templates/browser-support.hbs
https://emberjs.com/browser-support/ states v3 in present tense and talks about v4 in future tense, which is outdated.
Also v5 has been released some time ago but page does not mention it.
> Update browser-support.hbs to include v5

- .github/workflows/ci.yml
- package.json
> Update to node 20

- app/templates/releases/lts.hbs
Per [this message](https://discord.com/channels/480462759797063690/1131610462207873025/1164957530112409670) in the ember-js discord, let's add a couple of new columns (Bugfixes until and Security patches until) to the no longer maintained LTS table on the `releases/lts` route.
While glossing over this, I _think_ that I caught a few instances where we were showing the incorrect minor version / date for a few LTS versions as well, but definitely worth double checking them.
> Add non supported bugfix and security patch until dates

- app/templates/releases/lts.hbs
Per https://github.com/ember-learn/ember-website/pull/1083#issuecomment-1939708692, the last minor version column is a little bit prone to having stale data. Instead, let's just provide a link to a place where the reader can find all of the releases of Ember.
> releases/lts: drop last minor version column

- app/templates/releases/lts.hbs
It would be 36 added to the release date, but only 30 from promotion date
> Correct number of weeks added to promotion date

- data/team-member/krystan-huffmenne.md
- data/team-member/scott-newcomer.md
- tests/unit/controllers/teams-test.js
This PR adds Krystan HuffMenne to the Ember Data core team
and moves Scott Newcomber to alumni
> Adding Krystan HuffMenne to the Ember Data core team

- app/templates/browser-support.hbs
RFC: https://github.com/emberjs/rfcs/pull/984
> Update the browser support policy page

- data/team-member/chris-ng.md
- tests/unit/controllers/teams-test.js
> Alumni myself (chrisrng)

- app/controllers/teams.js
- app/templates/teams.hbs
- data/team-member/aaron-chambers.md
- data/team-member/chris-manson.md
- data/team-member/edward-faulkner.md
- data/team-member/james-davis.md
- data/team-member/katie-gengler.md
- data/team-member/kelly-selden.md
- data/team-member/krystan-huffmenne.md
- data/team-member/peter-meehan.md
- data/team-member/peter-wagenet.md
- data/team-member/preston-sego.md
- data/team-member/simon-ihmig.md
- tests/unit/controllers/teams-test.js
We discussed this at the learning team and decided that we should go ahead with the PR getting the right approvals from everyone who has a stake
> merge cli, typescript, and embroider teams

- app/components/mascots/mascot-list.hbs
- app/templates/logos.hbs
This MR works on the Copy/Content Updates to /logos/ page #1007 issue tasks:
1. Each section has an ID that can be used in the anchor link in order to navigate to a specific section
2. Added id to each Mascot ListItem li i.e `mascot.id`
3. Added the necessary sections
4. Added links to each instance of the Standard Art Set
5. Added the links to the mascot items specified in Standard Art Set
> Add /logos/ route new sections and anchor links

- app/components/mascots/mascot-list.hbs
- app/components/mascots/mascot-list/item.hbs
- app/styles/app.css
- app/styles/components/mascots.css
I found myself wanting to link to the Empress mascot recently so I added the ability to link to a particular mascot using an ID. 
Once this PR is merged you will be able to go to https://emberjs.com/mascots/#empress and it should scroll to the right part of the page and highlight the "target" mascot like this: 
Let me know if you have any questions :) 
Edit: here is a link with the preview app to allow you to test if it's working https://deploy-preview-805--ember-website.netlify.app/mascots/#empress
Second Edit: this functionality was added in https://github.com/ember-learn/ember-website/pull/1009 and this PR now just adds the highlight to the linked Mascot
> add ability to link to a particular mascot

- .github/workflows/ci.yml
This is unfortunate because now it means that we can't have percy snapshots from forks 😞
> rely on the github config for the PERCY_TOKEN

- app/components/teams/team.hbs
- app/helpers/dasherize.js
- package.json
- pnpm-lock.yaml
- tests/integration/helpers/dasherize-test.js
This doesn't add any visual indication on how to link to a team but it just allows you to manually link 👍 
Here is an example with the preview deploy https://deploy-preview-1140--ember-website.netlify.app/teams/#the-ember-tooling-core-team
> add the ability to link to a team on teams page

- app/templates/node-support.hbs
- app/templates/typescript-support.hbs
Note also: 
- https://github.com/emberjs/ember.js/pull/20957
- https://github.com/ember-learn/ember-styleguide/pull/532
> Add typescript support page

- app/components/teams/team/member.hbs
- app/styles/components/addon-tabs.css
- package.json
- pnpm-lock.yaml
- tests/acceptance/index-test.js
- tests/index.html
This is skipping _THREE_ majors...
but I want this:
- https://github.com/ember-learn/ember-styleguide/pull/532
But it's not released yet:
- ~~https://github.com/ember-learn/ember-styleguide/pull/533~~ released!
two new very important pages:
> Bump the styleguide

- app/templates/browser-support.hbs
This was incorrect ... versions are available via require('ember-source').supportedBrowser and can be seen here https://github.com/emberjs/ember.js/blob/main/lib/browsers.js
> Correct browser versions for 6.x

- app/styles/app.css
- app/templates/index.hbs
There hasn't anything for folks who are "somewhat familiar" with the framework.
This PR adds two new calls-to-action which link to existing pages:
- the quickstart -- for folks who don't want to read the tutorial (like if they've already read it), and they want to see how to make a new app, or refresh their memory on what the specific commands are
- the API reference -- for folks who are already using ember, and want to look something up.
> More calls to action
