ember-learn/ember-website

.github/pull_request_template.md

We should change this as the project matures.

Create an issue template for the GitHub repo

---

app/styles/app.scss
app/styles/pages/_faq.scss
app/templates/tomster/faq.hbs

fixes: #22

---

config/optional-features.json
package.json

Remove jQuery dependency

---

.template-lintrc.js
app/templates/learn/index.hbs

Replace usage of triple curlies with html-safe helper

---

app/styles/app.scss
app/styles/pages/_community.scss
app/templates/community/index.hbs

Community page

---

app/styles/_layout.scss
app/styles/app.scss
app/templates/mascots/commission-sent.hbs

Fixes #21 
While @patocallaghan did 99% of the work for the commissions page, this PR finishes of the last task to close the issue 👍 
Thanks again @patocallaghan 🎉

Commission sent page

---

.gitignore
.travis.yml
README.md

This is just fixing the readme as a result of #155 👍

fixing the Readme

---

app/components/ember-survey.js
app/router.js
app/styles/app.scss
app/styles/components/_survey-banner.scss
app/templates/application.hbs
app/templates/components/ember-survey.hbs
app/templates/ember-community-survey-2019.hbs
config/environment.js
tests/integration/components/ember-survey-test.js

Closes https://github.com/ember-learn/ember-website/issues/171
Ports the Ember Community Survey Banner from [the guidemaker-ember-template repo](https://github.com/ember-learn/guidemaker-ember-template/blob/master/addon/templates/components/ember-survey.hbs)

Add Ember Community Survey banner to site

---

.netlifyredirects
.travis.yml

Fixes #207 
Fixes #168 
Fixes #210 
Fixes #209 
Fixes https://github.com/ember-learn/ember-api-docs/issues/596

adding redirects for brand and meetup-assets

---

.netlifyredirects
app/templates/statusboard.hbs

It was unclear by the documentation that this was actually necessary 🤔 https://www.netlify.com/docs/redirects/#query-params
I will test this in the preview app and self merge if it fixes the problem

adding query params for api redirects

---

app/styles/components/_job-board-banner.scss
app/templates/ember-community-survey-2019.hbs
config/environment.js

This PR is in preparation for the survey ending at some point in the next 24 hours. I am preparing it so that it is ready to merge whenever it is time to end the survey.

turning off the survey

---

app/templates/ember-community-survey-2019.hbs

removed some of the old content to prep for new content

cleaning up 2019 page to prep for new content

---

app/templates/ember-community-survey-2019.hbs

Reverts ember-learn/ember-website#235

Revert "cleaning up 2019 page to prep for new content"

---

app/templates/editions/index.hbs

https://github.com/ember-learn/ember-website/pull/241 actually didn't end up fixing the issue (we have prember issues and ember app issues) 
I think this will fix it 👍 we should verify on the preview before merging 🎉

really fixing the tomster in the editions page

---

app/templates/ember-community-survey-2019.hbs

Minor edits and highlighting key takeaways to make it easier to digest

Minor edits

---

package-lock.json

Updates package lock for ember-styleguide

---

data/feature/module-unification.md

Update the MU statusboard entry

Update the MU section on the status board.

---

app/templates/releases/index.hbs

Update guides link to avoid redirect

---

data/project/ember/beta.md
data/project/ember/lts.md
data/project/ember/release.md

closes #295 
closes #296 
closes #297 
This is just porting over @kategengler's work, essentially rebasing on the releases refactor work done in #298 👍

updating beta, lts, and release for latest release

---

app/components/project-listing/template.hbs
app/styles/pages/_releases.scss
app/templates/releases/canary.hbs
app/templates/releases/index.hbs

- Fixing the sidebar contrast on the releases page
- Fixing some pages that were missing H1 elements
- Fixing some padding on releases

Minor accessibility fixes

---

app/styles/app.scss
app/templates/releases/index.hbs

Fix "false positive" Percy from https://github.com/ember-learn/ember-website/pull/306

In Percy, hide dynamic beta release "x days ago"

---

app/templates/guidelines.hbs

A quick change for the link in the guidelines.hbs

Issue #309 changing link for repository

---

.netlifyheaders

I have tested this locally and it does indeed fix the CORS issue that currently exists on the production website

fixing CORS on /data/* folder

---

blueprints/user/files/data/user/__name__.md

I assume at some point there was an actual list and users were expected to add to the bottom.  At this point there is no list, attempted better wordage that honors the spirit of the comment.

users blueprint: there is not a list to add to the bottom

---

package-lock.json
package.json

Bump ember-styleguide to get new footer link

---

data/team-member/melanie-sumner.md

This PR formally alumnizes Mel from the Learning Team

Alumnize Mel from the Learning Team

---

app/controllers/application.js

#354: fix: Fixes “Legal” link on navbar

---

data/meetup/chennai-india.md

Heres the link to the Chennai meetup group
https://www.meetup.com/Chennai-EmberJS/

Adding chennai to meetups page

---

.travis.yml
app/styles/app.css
app/templates/application.hbs
app/templates/index.hbs
lib/content-data-generator/index.js
package-lock.json
package.json
tests/acceptance/nav-bar-test.js

Using page header

---

app/templates/learn/index.hbs

link of tutorial has been fixed

broken link fix

---

app/highcharts-configs/application.js
app/styles/app.css
app/templates/releases/canary.hbs

this is an attempt to fix things that change every build so that Percy only reports real changes

fixing percy variablity

---

data/project/ember/beta.md
data/project/ember/release.md
data/project/emberData/beta.md
data/project/emberData/release.md

Not 100% sure what I'm doing here. Just compared to the previous time this stuff was updated, and tried to find info about the latest betas.

Updated data for release of 3.12 and beta of 3.13

---

ember-cli-build.js

this is for SEO and also to make the direct link work properly 👍

adding release/lts to prember

---

data/team-member/tobias-bieniek.md

I haven't had a lot of time and energy lately to do any meaningful contributions so I'm moving myself to alumni status for now.

team: Move myself to `alumni` team

---

app/templates/index.hbs
package-lock.json

I don't actually want to merge this until it makes it into ember-styleguide upstream but I wanted to demo what the `background-shapes` branch looked like on the website.
Looking good if I don't say so myself 😍

using new background shapes

---

app/templates/about/legal.hbs

@mansona is this the markup change you're looking for?
Biggest question I had was on the nesting of the `h1` tag. My general policy is to nest them within the section so that they label that area, but I wasn't able to find this in the styleguid.
Also unsure if leaving the `<strong>` was the right choice, or if it should replaced with a `<span class="bold">`.
Fixes #440

Update about/legal to comply with styleguide

---

app/components/tomster-list.js
app/controllers/mascots/index.js
app/styles/app.css
app/styles/components/tomster-list.css
app/templates/components/tomster-list.hbs
app/templates/mascots/index.hbs
package-lock.json

This was an attempt to fix the mascots page using just the css helpers available in the styleguide. As you can see from the inclusion of some CSS it didn't quite hit that goal 😞 
We should discuss ways to make this less necessary or if we will, in fact, need some custom CSS for this page
https://deploy-preview-375--ember-website.netlify.com/mascots/

Fix mascots

---

app/templates/security.hbs

fixes #442
I wasn't sure if there was a mockup somewhere of what this was supposed to look like. I just followed the class usage in #449 as an example. I'm happy to update it if necessary.

Update markup for Security page

---

app/templates/sponsors.hbs
data/sponsor/201-created.md
data/sponsor/addepar.md
data/sponsor/bookingsync.md
data/sponsor/bustle.md
data/sponsor/discourse.md
data/sponsor/dockyard.md
data/sponsor/linkedin.md
data/sponsor/livingsocial.md
data/sponsor/mhelabs.md
data/sponsor/tilde.md
data/sponsor/yahoo.md
data/sponsor/yapp.md

ALT texts for sponsors

---

package-lock.json
package.json

This just includes https://github.com/ember-learn/ember-styleguide/pull/257 which is a fix for the link styling in the footer and also the button link styling 👍

update ember styleguide

---

.github/workflows/ember-assets.yml

Updated because of https://github.com/simplabs/ember-asset-size-action/pull/4

update ember-assets definition

---

data/project/ember/beta.md
data/project/ember/release.md
data/project/emberData/beta.md
data/project/emberData/release.md

Fixes https://github.com/ember-learn/ember-website/issues/486.

Update releases page for 3.15

---

.netlifyredirects
app/router.js
app/templates/guidelines.hbs
ember-cli-build.js
tests/acceptance/visual-routes-test.js

Redirect /team to /teams

---

app/components/team-list-item/template.hbs
app/templates/components/tomster-list.hbs
app/templates/ember-users.hbs
app/templates/learn/examples.hbs
app/templates/learn/index.hbs
app/templates/sponsors.hbs
ember-cli-build.js
package-lock.json
package.json

This is required to prevent the issues where the JS was crashing because of integrity checks. If you want more information on why this is required you can check out this issue: https://github.com/ef4/prember/issues/52

remove ember-cli-ifa

---

app/templates/learn/index.hbs

Replacement for https://github.com/ember-learn/ember-website/pull/470 as the fork has been deleted
Fixes https://github.com/ember-learn/ember-website/issues/438

Updated markup for Learning Ember.js page

---

app/templates/community/meetups-getting-started.hbs
app/templates/community/meetups/assets.hbs

Closes https://github.com/ember-learn/ember-website/pull/464
This is just creating a new branch for #464 because the fork has been deleted 👍

Updated markup for Community - Meetups - Assets page

---

app/templates/learn/examples.hbs

This is just creating a new branch for https://github.com/ember-learn/ember-website/pull/467 because the fork has been deleted 👍 
Closes #439

Updated markup for Learn - Examples page

---

app/controllers/application.js
app/routes/application.js
app/templates/application.hbs
package-lock.json
package.json

Fixes https://github.com/ember-learn/ember-website/issues/457
This just updates the styleguide to make use of https://github.com/ember-learn/ember-styleguide/pull/259 and uses it correctly 👍

fix internal links - make sure they are Ember transitions

---

app/templates/index.hbs

Updates text now that tickets are on sale.

Updates EmberConf CTA text

---

app/styles/app.css
app/styles/components/brand-logos.css
app/templates/logos.hbs

Fixes https://github.com/ember-learn/ember-website/issues/441

implement logos page

---

app/styles/app.css
app/styles/legacy/form.css
app/templates/mascots/commission.hbs
app/templates/mascots/faq.hbs
app/templates/mascots/payment-sent.hbs
app/templates/mascots/payment.hbs

Fixes https://github.com/ember-learn/ember-website/issues/444
This PR really falls into the "not great, but good enough for now" category 🙈 It is no worse than current production, and actually fixes a bug on https://emberjs.com/mascots/payment/ 😂

Mascots Commission Pages

---

app/styles/app.css
app/styles/components/faqs.css
app/templates/editions/index.hbs
app/templates/editions/octane.hbs

Fixes https://github.com/ember-learn/ember-website/issues/447

Update Editions pages

---

app/templates/editions/index.hbs
app/templates/editions/octane.hbs

I think the last merge from master didn't include the latest content from the editions pages, this just brings the latest content that is currently on master into this branch 👍

update content on editions pages

---

app/templates/index.hbs

Fixes https://github.com/ember-learn/ember-website/issues/368

add content for community resources section

---

app/router.js
app/routes/team-redirect.js
app/templates/application.hbs
app/templates/index.hbs
package-lock.json
package.json

This just has a few fixes for small things that I noticed when testing the completed redesign. Each commit comment describes what has changed 👍 
I've also updated the styleguide so it fixes a bunch of SVG issues: https://github.com/ember-learn/ember-styleguide/issues/266 and https://github.com/ember-learn/ember-styleguide/issues/268

Minor landing page improvements

---

app/models/sponsor.js
blueprints/sponsor/files/data/sponsor/__name__.md
data/sponsor/cardstack.md
data/sponsor/simplabs.md
lib/content-data-generator/index.js

Fixes https://github.com/ember-learn/ember-website/issues/472

Sponsor image alt

---

data/team-member/todd-jordan.md

Hey, if you haven't heard I'm taking a minor break from Ember core team contributions to focus on things happening in other areas of my life for a bit.  This is me making it "official"

Moving myself to alumni

---

app/templates/index.hbs

On very small screen (iphone SE specifically) the button groups on the homepage would wrap with some spacing issues.

improve homepage button spacing on very small screens

---

app/templates/index.hbs

This is just splitting @MelSumner 's work from #558 into different PRs 👍
Fixes https://github.com/ember-learn/ember-styleguide/issues/284

add line break to title on landing page

---

app/styles/components/addon-tabs.css
app/templates/components/addon-tabs.hbs

This is just splitting @MelSumner 's work from #558 into different PRs 👍
Fixes https://github.com/ember-learn/ember-website/issues/521

adding initial addons to tabs

---

app/templates/index.hbs

This is just splitting @MelSumner 's work from #558 into different PRs 👍
Fixes https://github.com/ember-learn/ember-website/issues/551

updating home page with updated content

---

app/templates/index.hbs

Adds more unofficial resources to the "Books and blogs" list.

Update "books and blogs" content on home page

---

data/project/ember/beta.md
data/project/ember/release.md
data/project/emberData/beta.md
data/project/emberData/release.md

Based on https://github.com/ember-learn/ember-website/pull/587
I'm about to go on vacation, so figured could submit this for now. Please commit / merge / close at will! 
Figured it's a good incremental-ish step forward?

📝 Document how to update /releases page

---

app/components/addon-tabs.js
app/templates/components/addon-tabs.hbs
app/templates/components/addon-tabs/panel.hbs
app/templates/components/addon-tabs/tab.hbs
tests/integration/components/addon-tabs-test.js

AddonTabs keyboard improvements

---

app/styles/components/homepage-image-grid.css
app/templates/components/homepage-image-grid.hbs

As demonstrated in #600 
Also fixes a typo :)

Fix vertical scrollbar in homepage-image-grid

---

app/templates/releases/lts.hbs

Update LTS schedule for 3.16

---

app/templates/index.hbs

Fixes https://github.com/ember-learn/ember-website/issues/615.

Fix typo on index page copy

---

.github/ISSUE_TEMPLATE/bug_report.md
app/templates/index.hbs
app/templates/learn/index.hbs
data/feature/router-service.md

Updating the links with the release path
https://github.com/ember-learn/ember-website/issues/289

feat : release path in the url #289

---

config/environment.js

removing survey banner via config

removing survey banner

---

package-lock.json
package.json

Redid #593 
Based on master and found a different way to update specific transitive dependencies so I didn't purge the lock file in this MR.

Install ember-cli-babel-polyfills

---

data/team-member/sivakumar-kailasam.md

👋🏻 I'm unable to spend as much time as I used to as a core contributor, so I'm moving myself to alumni status.

Moving myself to alumni 

---

data/team-member/jen-weber.md

Hi everyone, with Octane shipped, I would like to spend more of my open source time directly on Learning Team efforts. As I will not be attending weekly FW team meetings or F2F, I think it's best to be a framework emeritus.

Moving myself (Jen) to solely the Learning Team

---

app/styles/components/ember-survey.css

Fixed contrast ratio

---

app/styles/components/homepage-image-grid.css
app/templates/community/index.hbs

Fixed the blur image

---

app/templates/learn/index.hbs

Fix ember engines guides link

---

app/templates/releases/lts.hbs

Explicitly identify projects that have LTS support (Ember.js, Ember CLI, Ember Data).

Explicitly identify projects that have LTS support

---

app/components/black-lives-matter-banner.hbs
app/components/black-lives-matter-banner.js
app/router.js
app/styles/app.css
app/templates/application.hbs
app/templates/community/black-lives-matter.hbs
app/templates/index.hbs

This is the change that was discussed at the Steering Committee 👍

Add black-lives-matter route

---

app/templates/application.hbs

Added Contribution link

---

.stylelintrc
app/styles/components/addon-tabs.css
app/styles/components/brand-logos.css
app/styles/components/cta-emberconf.css
app/styles/components/ecosystem-icons.css
app/styles/components/faqs.css
app/styles/components/homepage-image-grid.css
app/styles/components/release-timeline.css
app/styles/components/surveys.css
app/styles/legacy/form.css

Fixing the CSS lint issue 
- npm run lint:style -- --fix
- changed order of two css rules

Fix CSS lint errors #671

---

data/project/ember/beta.md
data/project/ember/release.md
data/project/emberData/beta.md
data/project/emberData/release.md

Updated Releases pages for Ember v3.22 release

---

.eslintrc.js
app/components/ember-survey.js
app/components/high-charts.js
app/controllers/community/meetups/index.js
app/models/project.js
app/routes/application.js
package-lock.json
package.json

As part of https://github.com/ember-learn/ember-website/issues/672 , fixing three other linting issues.
what-wg-fetch addition is due to test failing. Reference taken from - https://github.com/ember-cli/ember-fetch/issues/547
Have tested this in browser and running 'ember t' 
@ijlee2 - Kindly review this PR as well.

Fixed three eslint issues - 

---

app/templates/releases/lts.hbs

This pull request closes https://github.com/ember-learn/ember-website/issues/687. I added an example (Ember 2.x) to illustrate how LTS's may be assigned.

Clarified LTS schedule

---

app/templates/index.hbs

Add EmberObserver link

---

app/styles/components/ecosystem-icons.css

Addresses #550 
`pointer-events: none` seems to be the simplest solution.

Removes pointer interactivity from grid dots

---

app/adapters/application.js
app/models/meetup.js
app/models/project.js
app/models/showcase.js
app/models/sponsor.js
app/models/team-member.js
app/models/tomster.js
app/models/user.js
app/serializers/application.js
tests/unit/models/project-test.js

Octanify adapters, models and serializers

---

app/controllers/application.js
app/controllers/ember-users.js
app/controllers/releases/index.js
app/controllers/sponsors.js
app/controllers/team.js

This should address the controllers in issue #721
Closes #721

Convert controllers to native classes part one

---

app/controllers/community/meetups/index.js
app/controllers/ember-community-survey-2016.js
app/controllers/ember-community-survey-2017.js
app/controllers/ember-community-survey-2018.js
app/controllers/ember-community-survey-2019.js
app/controllers/mascots/index.js

Convert controllers to native class syntax part two

---

app/routes/application.js
app/routes/ember-community-survey-2016.js
app/routes/ember-community-survey-2017.js
app/routes/ember-community-survey-2018.js
app/routes/ember-community-survey-2019.js
app/routes/statusboard.js
app/routes/team-redirect.js

Convert routes to native classes part two

---

app/routes/community/meetups/index.js
app/routes/ember-users.js
app/routes/learn.js
app/routes/mascots.js
app/routes/releases.js
app/routes/releases/beta.js
app/routes/releases/canary.js
app/routes/releases/index.js
app/routes/releases/lts.js
app/routes/releases/release.js
app/routes/sponsors.js
app/routes/team.js

Convert routes to native classes part one

---

app/components/cta-ember-community-survey.hbs
app/components/cta-ember-community-survey.js
tests/integration/components/cta-ember-community-survey-test.js

Octanify <EmberSurvey> component Part 1

---

app/router.js
app/templates/browser-support.hbs
tests/acceptance/browser-support-test.js

Adds a browser support policy page, as described in the [new browser support policy RFC](https://github.com/emberjs/rfcs/blob/master/text/0685-new-browser-support-policy.md).

Adds Browser Support Policy Page

---

.eslintrc.js
.template-lintrc.js
app/controllers/teams.js
app/templates/ember-community-survey-2019.hbs
app/templates/mascots/payment.hbs

Now that all components are Glimmer components, we can remove the global exceptions that we had added to `.eslintrc.js` and `.template-lintrc.js`.

Fixed lint errors

---

app/components/ember-community-survey/section.hbs
app/styles/components/survey-section.css
app/templates/ember-community-survey-2016.hbs
app/templates/ember-community-survey-2017.hbs
app/templates/ember-community-survey-2018.hbs
app/templates/ember-community-survey-2019.hbs
app/templates/ember-community-survey-2020.hbs
app/templates/ember-community-survey-2021.hbs
tests/integration/components/ember-community-survey/section-test.js

Resolves https://github.com/ember-learn/ember-website/issues/767

Automatically alternate survey background

---

app/controllers/ember-community-survey-2020.js
app/utils/highcharts.js
app/utils/highcharts/pie-chart.js
tests/unit/utils/highcharts/pie-chart-test.js

I would like to start refactoring the code in `ember-community-survey` controller files. As a proof of concept, I created `PieChart` class, which can replace 2 instances of hard-coded chart options.
I created a class that accepts a minimum set of arguments. By creating a class, the controllers don't need to be aware that Highcharts is used to create charts, or that a future major version of Highcharts may require a different configuration. By creating a class, we can also write unit tests for what the configuration object should look like.
My long-term goal is to write a class for every chart type that we have used for the survey results pages. The chart types are:
- areaspline (4 instances)
- bar (6)
- column (36)
- columnrange (1)
- pie (2)
- spline (8)

Created PieChart class

---

app/controllers/ember-community-survey-2018.js
app/controllers/ember-community-survey-2020.js
app/utils/highcharts.js
app/utils/highcharts/horizontal-bar-chart.js
app/utils/highcharts/pie-chart.js
tests/unit/utils/highcharts/horizontal-bar-chart-test.js
tests/unit/utils/highcharts/pie-chart-test.js

A continuation of #768, where I started refactoring the code in `ember-community-survey` controller files. In this pull request, I created `HorizontalBarChart` class, which can replace 3 instances of hard-coded chart options. (A 4th instance had a binary response so I used `PieChart` instead.)
I created a class that accepts a minimum set of arguments. By creating a class, the controllers don't need to be aware that Highcharts is used to create charts, or that a future major version of Highcharts may require a different configuration. By creating a class, we can also write unit tests for what the configuration object needs to look like.
The first 4 commits show step-by-step instructions for creating the `HorizontalBarChart` class. I think these steps can help a new contributor with …

Create HorizontalBarChart class

---

app/templates/index.hbs

Closes #790.
Do I need to add a `title` attribute?

Add link to Ember Data guides

---

app/controllers/ember-community-survey-2020.js
app/utils/highcharts.js
app/utils/highcharts/vertical-bar-chart.js
tests/unit/utils/highcharts/vertical-bar-chart-test.js

A continuation of #784. In this pull request, I created `VerticalBarChart` class, which can replace 80-100 instances of hard-coded chart options.
I created a class that accepts a minimum set of arguments. By creating a class, the controllers don't need to be aware that Highcharts is used to create charts, or that a future major version of Highcharts may require a different configuration. By creating a class, we can also write unit tests for what the configuration object needs to look like.
As a proof of concept, I converted configuration objects in 2020 survey. I plan to ask the community for help with converting objects in 2016 - 2019. (I may do 2016 because it's more difficult.)

Created VerticalBarChart class (Part 1)

---

app/controllers/ember-community-survey-2016.js

Closes https://github.com/ember-learn/ember-website/issues/797.

Used VerticalBarChart to create 2016 survey responses

---

app/controllers/ember-community-survey-2018.js

This fixes issue https://github.com/ember-learn/ember-website/issues/795

 #issue-795 convert column charts to VerticalBarChart class

---

app/templates/about/legal.hbs
app/templates/mascots/commission.hbs
app/templates/security.hbs

Fix various links across the website

---

app/controllers/releases/lts.js
app/templates/releases/lts.hbs

issue-788 remove 3.16 LTS version

---

app/controllers/ember-community-survey-2017.js
app/controllers/ember-community-survey-2019.js
app/templates/ember-community-survey-2019.hbs

Related issue: #796 
@fozy and I, I believe, have converted configuration objects for vertical bar chart that are currently live. However, there are still ~20 vertical bar charts that are not live that need to be converted. Let's do this in a 2nd pull request.

Use VerticalBarChart to create 2019 survey responses (Part 1 of 2)

---

app/templates/sponsors.hbs
tests/acceptance/sponsors-test.js

Fixes #828

---

app/templates/editions/octane.hbs
tests/acceptance/editions/octane-test.js

Fixes issue [#827](https://github.com/ember-learn/ember-website/issues/827)

Address 2 accessibility issues in /editions/octane #827

---

app/templates/ember-users.hbs
app/templates/logos.hbs

After renaming the default branch name to `main`, I searched for URLs to `ember-website` that needed to be updated.

Updated default branch name

---

data/user/orbcare.md

Remove company

---

app/controllers/ember-community-survey-2019.js

Used VerticalBarChart to create 2019 survey responses

---

data/team-member/jessica-jordan.md

I won't be able to spend the amount of time necessary to be a core contributor for a while and therefore would like to alumnize. Thank you all for being such an awesome team and see you all soon :heart: 🙇🏾‍♀️

Alumnize Jessica

---

app/components/highcharts.js
app/controllers/ember-community-survey-2016.js
app/controllers/ember-community-survey-2017.js
app/controllers/ember-community-survey-2018.js
app/controllers/ember-community-survey-2019.js
app/controllers/ember-community-survey-2020.js
app/templates/ember-community-survey-2016.hbs
app/templates/ember-community-survey-2017.hbs
app/templates/ember-community-survey-2018.hbs
app/templates/ember-community-survey-2019.hbs
app/templates/ember-community-survey-2020.hbs
tests/integration/components/highcharts-test.js

- Update highcharts component to accept instance of a chart as @chart
- Update usage of highcharts component in templates
- Update controllers to pass instance of Chart object
@ijlee2 I have handled not receiving a '@chart' argument to support the current tests for 'ember-community-survey/section' - we don't pass a '@chart' argument here. Not sure if this is the right way to go.
Closes #845

Remove unused Highcharts code (Part 1)

---

data/team-member/kenneth-larsen.md

I will not be able to spend the time needed anymore to be part of the core team. Thank you for letting me be part of this wonderful team for almost three years 💖

Alumnize Kenneth

---

app/components/mascots/mascot-list/item.hbs
app/styles/components/homepage-image-grid.css
ember-cli-build.js
package-lock.json
tests/integration/components/mascots/mascot-list/item-test.js

Following up on #769 this makes the mascots page also use responsive images.

Make Mascots images responsive

---

data/team-member/dan-gebhardt.md

Although I will continue to be a proud member of the Ember community, I do not wish to remain in leadership positions without being able to give them the full attention they deserve. It's been a privilege to work with everyone on this incredible project.

Alumnize dgeb

---

package-lock.json
package.json

- https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md

Updated ember-auto-import to v2.1.0

---

app/locations/trailing-history.js
app/utils/format-url.js
tests/unit/utils/format-url-test.js

Fixing https://github.com/ember-learn/ember-website/issues/862 - mascots filtering
This is alternative to https://github.com/ember-learn/ember-website/pull/863
The fix is a bit hacky...
I think it works but is there a better solution?

fix issue-862-mascots

---

data/team-member/isaac-lee.md

Hallo Leutchen. Today I'll be an alum so that I can work on new goals soon. Look forward to see what you achieve next year!

Alumnized Isaac

---

app/templates/teams.hbs

Slight adjustment to match our current verbiage around core teams.

Fix team name

---

app/templates/index.hbs

replaced `too—` with `to` in this paragraph
<br/>

updated typo in paragraph

---

data/team-member/kris-selden.md

I alumnized Oct 22, 2021 but forgot to do this PR.

Alumnize Kris Selden

---

.gitignore
app/components/invasion-of-ukraine-banner.hbs
app/components/invasion-of-ukraine-banner.js
app/router.js
app/styles/app.css
app/styles/components/invasion-of-ukraine-banner.css
app/templates/application.hbs
app/templates/community/invasion-of-ukraine.hbs

As you already know we have war in Ukraine right now
Ukrainian community want to propose a banner for sharing information about Russian invasion
I know that open source it's not about politics - but it's war 
Millions of people are struggling including members of Ember community
Thank you for understanding

Add invasion of Ukraine info banner and page

---

app/components/invasion-of-ukraine-banner.hbs
app/templates/community/invasion-of-ukraine.hbs

If merged, this PR makes the following changes: 
- changes the banner text to "Support Ukraine"
- removed flag emoji since it doesn't render on Windows
- changed references to "Russia" into "the Russian Government" or "The Russian Military" as appropriate
- removed language that could be considered emotionally manipulative
- removed requests/links to support the military directly (we support civilians and charities)
- removed link to hospitallers (a religious military order)
- visited each link and updated the links and prose attached to each charity as was appropriate, for clarity and brevity
- added reminder to contact elected officials and let them know of your support
The language could probably be edited further if anyone has suggestions.

updated prose for the Support Ukraine page

---

app/templates/application.hbs
app/utils/header-links.js

As discussed previously, updating site banners: 
Updates banners so only a single banner shows at a time
Adds link in community nav dropdown (and re-arranges the dropdown "sections" a little differently)

updates site banners, adds navbar item

---

data/team-member/igor-terzic.md

Formally alumnize Igor

---

data/team-member/chad-hietala.md

This experience has been transformational and truly shaped me as a developer. Thank you all!

Aluminize Myself

---

app/templates/releases/index.hbs

Fix typo for modifying

---

data/team-member/godfrey-chan.md

We have some big news to share with you today: Godfrey is now an emeritus member of the core team!
I joined the framework core team six (!) years ago in 2016, in large part thanks to the synergy with my work at Tilde and my personal interest/goals at the time. Commits (also mistakes and bugs, probably) were made along the way, but the real journey was the friends we made along the way!
I am still at Tilde, but due to shifting responsibilities/priorities/focus at work, we can no longer justify me spending much work time on Ember this year, and I am not in a position to spend more personal time either. So I decided to alumn-ize to make the expectations clear/explicit, and make room for others to step in and pick things up where I left them off.
I'll still be somewhat around, on Discord and …

What an Incredible Journey! 

---

app/templates/releases/index.hbs

Per [RFC 0800](https://rfcs.emberjs.com/id/0800-ts-adoption-plan/), documenting our approach to SemVer for TS. I added text describing how we handle Node while I was at it.
Resolves #955.

Describe TS and Node policies in SemVer discussion

---

app/templates/index.hbs

I added the podcasts mentioned in this [issue](https://github.com/ember-learn/ember-website/issues/917) except for "The Ember Report" which looks pretty dead (+ their website is down)
[#917](https://github.com/ember-learn/ember-website/issues/917)

Add additional podcasts

---

app/utils/header-links.js

Update RFCs link

---

app/templates/security.hbs

Update CVE (Common Vulnerabilities and Exposures (CVE®)) link in the security page to their new website

---

app/templates/index.hbs

Helps address https://github.com/ember-learn/ember-website/issues/917

Move dead podcasts to bottom of list

---

app/templates/index.hbs

Updating some language on the home page for trademark renewal purposes: 
With updates:

updating some page language for trademark renewal purposes

---

data/team-member/chris-krycho.md

Just what it says on the tin. 👋🏼

Chris Krycho alumnizing from Framework

---

data/team-member/bert-de-block.md

Thanks again everyone for the opportunity! It's been short but sweet! ❤️

Remove Bert De Block from CLI team

---

data/team-member/dan-freeman.md

I won't be dropping off the face of the earth, but given shifts in my focus at work and in my personal availability, I won't realistically be able to be a driving force behind any major TS work going forward

Alumnize Dan Freeman

---

data/team-member/david-hamilton.md

Alumnize David Hamilton

---

app/models/sponsor.js
app/templates/sponsors.hbs
data/sponsor/auditboard.md
data/sponsor/cardstack.md
data/sponsor/linkedin.md
data/sponsor/mainmatter.md
data/sponsor/tilde.md
lib/content-data-generator/index.js

Sponsor updates

---

app/templates/logos.hbs

##What does this PR do?
Fixes #1051 
Closes https://github.com/ember-learn/ember-website/pull/1054
Closes https://github.com/ember-learn/ember-website/pull/1053
##Changes made
at *ember-website\app\templates\logos.hbs* added *target="_blank* to <a> tag and changes *href* to **/pdfs/Ember-Brand-Guidelines.pdf**
##video
https://github.com/ember-learn/ember-website/assets/53528683/a6e2e8c2-6aae-4a8b-a076-8e24984b0b37

fix: Fixed 404 ERROR

---

data/team-member/chris-krycho.md

End of an era! I started working on types for Ember (actually in [Flow][flow], because it had features TS did not and which Ember Classic required!) almost exactly 7 years ago. In doing a triage pass yesterday on the [ember-cli-typescript][ects], I realized that while there is still a lot to be done to take Ember’s TS story from its current state of “quite good, modulo Ember Data” to “really and unambiguously great across the board”, we have actually solved every single issue the Typed Ember team [identified][ec2019] back at EmberConf 2019, some 4½ years ago.
[flow]: https://flow.org
[ects]: https://github.com/typed-ember/ember-cli-typescript
[ec2019]: https://v4.chriskrycho.com/2019/emberconf-2019-typed-ember-team-report.html
I’m incredibly proud to have been a part of that, and grateful …

Alumnize Chris Krycho from Ember TS team

---

app/routes/community/meetups/index.js
app/routes/ember-users.js
app/routes/learn.js
app/routes/mascots.js
app/routes/releases.js
app/routes/releases/beta.js
app/routes/releases/canary.js
app/routes/releases/lts.js
app/routes/releases/release.js
app/routes/sponsors.js
app/routes/teams.js

See https://deprecations.emberjs.com/v3.x/#toc_implicit-injections

Fix implicit injection deprecation

---

app/controllers/releases/lts.js
app/routes/releases/lts.js
app/templates/releases/lts.hbs
data/project/emberData/lts.md
tests/unit/routes/releases/lts-test.js

Update LTS page for data breaking lockstep

---

app/templates/index.hbs

Remove Ember Weekend podcast

---

app/adapters/application.js
package-lock.json
package.json

This now prevents the first load of data on each page that has been pre-rendered with fastboot and prember 👍

add ember-data-fastboot to enable the shoebox across the site

---

app/templates/browser-support.hbs

Pending: 
- https://github.com/ember-learn/ember-website/pull/1088
- v6.0.0 release

Ember 6 browser policy

---

app/components/teams/team/member.hbs
app/models/team-member.js
blueprints/team-member/files/data/team-member/__name__.md
lib/content-data-generator/index.js

Add generic social link option to team member
